# Generated by Django 4.0.3 on 2022-03-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=120, unique=True)),
                ('designation', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('salary', models.PositiveIntegerField()),
            ],
        ),
    ]
